### ISSUE TITLE
Prefix must be unicode error

### ISSUE THREAD

**Issue by zhoudaqing** [inuitwallet/crypto-daio#1]
command：python2 manage.py runserver

error info：
```
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Unhandled exception in thread started by <function wrapper at 0x10df3dde8>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 48, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/usr/local/lib/python2.7/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/usr/local/lib/python2.7/site-packages/channels/asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "/usr/local/lib/python2.7/site-packages/channels/asgi.py", line 61, in _make_backend
    asgi_layer = backend_class(**config)
  File "/usr/local/lib/python2.7/site-packages/asgi_redis/core.py", line 65, in __init__
    assert isinstance(self.prefix, six.text_type), "Prefix must be unicode"
AssertionError: Prefix must be unicode
```

**Comment by zhoudaqing** [comment]
Unhandled exception in thread started by <function wrapper at 0x10ca8dc80>
Traceback (most recent call last):
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/channels/apps.py", line 6, in <module>
    import daphne.server  # noqa
  File "/Users/zhoudaqing/sourcecode/PycharmProjects/crypto-daio/venv/lib/python2.7/site-packages/daphne/server.py", line 196
    async def handle_reply(self, protocol, message):
            ^
SyntaxError: invalid syntax

**Comment by zhoudaqing** [comment]
and python3 run:

(venv) ➜  crypto-daio git:(master) ✗ python3 manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10309ef28>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 118, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'channels' has no attribute 'delay'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/usr/local/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'channels.delay'
